theme = "tokyonight"

[editor]
cursorline = true
cursorcolumn = true
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.lsp]
display-inlay-hints = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "┆"

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

[keys.normal.space]
v = ":sh zellij run -- cargo clippy --tests -- -Dwarnings"
n = ":sh zellij run -- cargo run"
t = ":sh zellij run -- cargo test"
i = ":sh zellij run -- ~/.config/aichat/rag.sh"
