# Initialize completion system
autoload -Uz compinit
compinit

# Set gpg to manage SSH connections
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# Set default text editor to helix
export EDITOR=/usr/bin/helix
export VISUAL=$EDITOR
alias vi="nvim"
alias hx="helix"

export TERRAFORM_KEY=/home/andres/deepc/blinky/ci/terraform/terraform
export DEEPC_KEY=/home/andres/.ssh/gitlab_deepc.pub
export PERSONAL_KEY=/home/andres/.ssh/andres_key.pub
export GOBIN=$HOME/go/bin

export PATH=/home/andres/go/bin:/home/andres/.cargo/bin:/home/andres/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

command -v flux >/dev/null && . <(flux completion zsh)
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)
source /usr/share/nvm/init-nvm.sh
source /home/andres/.config/broot/launcher/bash/br

eval "$(starship init zsh)"
eval "$(atuin init zsh)"

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/andres/.cache/yay/scratchjr-desktop-git/src/ScratchJr-Desktop/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/andres/.cache/yay/scratchjr-desktop-git/src/ScratchJr-Desktop/node_modules/tabtab/.completions/electron-forge.zsh
export PATH=/home/andres/bin:$PATH

[[ -e "/home/andres/lib/oracle-cli/lib/python3.12/site-packages/oci_cli/bin/oci_autocomplete.sh" ]] && source "/home/andres/lib/oracle-cli/lib/python3.12/site-packages/oci_cli/bin/oci_autocomplete.sh"

alias oci='docker run --rm -v "$HOME/.oci:/oracle/.oci" oci'
